apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: aankalan        

manifests:
  kustomize:
    paths:
      - ./k8s//overlays/dev

requires:
  - path: ./spring-boot-k8s

portForward:
- resourceType: deployment
  resourceName: web1
  port: 8080
  localPort: 8080
