apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Points to the directories containing the child kustomizations
resources:
  - ./spring-boot-k8s-1
  - ./spring-boot-k8s-2

# Transformations applied to ALL children
labels:
- pairs:
    product: aank
    env: base
