# mariadb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  # Replace "strong_password" with your desired strong password
  MYSQL_ROOT_PASSWORD: "strong_password"


