apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
labels:
- includeSelectors: true
  pairs:
    env: dev
resources:
  - ../base
# Add a prefix to all resource names
# namePrefix: dev-
