apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aankalan-applicationset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      # we can use git level "tests" on pr-merge to enforce rules that only one can be active.
      elements:
      - cluster: hdc-prod
        drStatus: active # values are active, passive, down, na
        url: https://kubernetes.default.svc
      - cluster: mndc-prod
        drStatus: passive
        url: https://kubernetes.default.svc
      - cluster: hdc-qa
        drStatus: na
  template:
    metadata:
      name: '{{.cluster}}-aankalan'
    spec:
      project: aankalan
      source:
        repoURL: <url of aankalan argocd repo>
        targetRevision: HEAD
        path: kustomize/overlays/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: aankalan