apiVersion: v1
kind: Service
metadata:
  name: solr-standalone-service
spec:
  selector:
    app: solr-standalone
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983 # Solr's default port
  clusterIP: None # This makes it a "Headless Service", which is often used with StatefulSets to allow direct access to individual pods.
