apiVersion: batch/v1
kind: Job
metadata:
  name: admin
  labels:
    app: admin
spec:
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: admin
        command: ["./db-sleep.sh"] 
        env:
        - name: DB_HOST
          value: mariadb-service
        - name: DB_PORT
          value: "3306"
        - name: ROOT_DB_USER
          value: root
        - name: ROOT_DB_PASSWORD # The MySQL image expects this specific env var
          valueFrom:
            secretKeyRef:
              name: mariadb-secret # Name of the Secret object
              key: MYSQL_ROOT_PASSWORD # Key in the Secret that contains the password
      restartPolicy: Never
  backoffLimit: 4
  ttlSecondsAfterFinished: 100

  

