apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps

# Points to the directories containing the child kustomizations
resources:
  - ../../base

# Transformations applied to ALL children
labels:
- pairs:
    product: aankalan
    env: dev
