spring.application.name=demo
server.port=9100

management.endpoints.web.exposure.include=*
http.mappers.json-pretty-print=true
management.endpoint.env.show-values=ALWAYS

aws_s3_url=https://${config.aws_s3_ip}/some-long-suffix
aws_s3_pool_max=300
aws_s3_access_key=${secret.aws_s3_access_key}


